qbt_translation_grid:
    pattern:  /translation/grid
    defaults: { _controller: "QBTTranslationBundle:Edition:grid" }

qbt_translation_list:
    pattern:  /translation/list
    defaults: { _controller: "QBTTranslationBundle:Edition:list" }

qbt_translation_update:
    pattern:      /translation/update
    defaults:     { _controller: "QBTTranslationBundle:Edition:update" }
    requirements: { _method: POST }

qbt_translation_new:
    pattern:  /translation/new
    defaults: { _controller: "QBTTranslationBundle:Edition:new" }

qbt_translation_invalidate_cache:
    pattern:  /translation/invalidate-cache
    defaults: { _controller: "QBTTranslationBundle:Edition:invalidateCache" }
